int a = 0;
int b = 14;
int c = -8;
int d = 24;
int e = 13;
int max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.Write("max = ");
Console.WriteLine(max);